knp_gaufrette:
  stream_wrapper: ~

  adapters:
    profile_adapter:
      local:
        directory: "%kernel.project_dir%/public/images/avatars"
    bookCover_adapter:
      local:
        directory: "%kernel.project_dir%/public/images/bookcovers"

  filesystems:
    profile_fs:
      adapter: profile_adapter
    bookCover_fs:
      adapter: bookCover_adapter

vich_uploader:
  db_driver: orm
  storage: gaufrette

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
  #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
  metadata:
    type: attribute

  mappings:
    avatarImg:
      uri_prefix: /images/avatars
      upload_destination: "%kernel.project_dir%/public/images/avatars"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    bookCover:
      uri_prefix: /images/bookcovers
      upload_destination: "%kernel.project_dir%/public/images/bookcovers"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

when@test:
  knp_gaufrette:
    adapters:
      product_adapter:
        local:
          directory: "%kernel.cache_dir%/images"
